---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Load the libraries and get a glimpse of the Vemurafinib data
```{r, warning = FALSE, message = FALSE}
# Load the basket library.
library(basket)
library(tibble)
library(dplyr)

# Set to sequential execution to get rid of warning.
if (require(foreach)) {
  foreach::registerDoSEQ()
}

# Take a look at the Vemurafinib data.
data(vemu_wide)
vemu_wide %>% glimpse
```

# Fit the full Bayes MEM model

```{r}
fit <- mem_full_bayes(responses = vemu_wide$responders,
                      size = vemu_wide$evaluable,
                      name = vemu_wide$baskets,
                      p0 = 0.15)
fit
```

# Plot the basket densities

```{r}
plot_density(fit)
```

# Plot the posterior exchangeability

```{r}
plot_posterior_exchangeability(fit, size = 1.5, label = TRUE)
```

# Plot the exchangeability MAP

```{r}
plot_exchangeability(fit, size = 1.5)
```

